config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :questions

  get "survey/index"
  
  post "survey/start"

  get "survey/question"
  
  post "survey/question"

  post "survey/answer"

  get "survey/result"
  
  post "answers/create"
  
  post "answers/destroy"

  get "signup" => "users#new"

  get 'edit' => 'users#edit'

  get "/login" => "sessions#new"

  post "login" => "sessions#create"

  delete "logout" => "sessions#destroy"
  resources :users

end

app/models/answer.rb
class Answer < ActiveRecord::Base
	belongs_to :question
end

app/models/question.rb
class Question < ActiveRecord::Base
	has_many :answers

	def answer
		uncorrect
	 	answers.select {|f| f.correct}[0]
  	end	
  
  	def uncorrect
	 	answers.each {|f| f.correct = false}
  	end	
  
  	def answer= answer
	 	if !answer.nil?
		answer.correct = false
		end
	 
		if answers.include? answer
			answer.correct = true
	 	else
			answers << answer
			answer.correct = true
	 	end
  	end

end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	validates :first_name, presence: true, length: { maximum: 50 }
	validates :last_name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 },
			format: { with: VALID_EMAIL_REGEX },
			uniqueness: { case_sensitive: false }

	def admin?
		self.role == 'admin'
	end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
	def create
	 @question = Question.find(params[:question])
	 text = params[:text]
	 correct = params[:correct] == "1"
	 new = Answer.create(text: text, correct: correct, question_id: @question.id)
	 
	 if new.correct
		@question.answer = new
	 end
	 
	 redirect_to question_path(@question)
  	end
  
  def destroy
	 @question = Question.find(params[:question])
	 @answer = Answer.find(params[:answer])
	 @answer.destroy
	 redirect_to question_path(@question)
  end
  


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_user
  	redirect_to '/login' unless current_user
  end

  def require_admin
    redirect_to root_path unless current_user.admin?
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_action :require_user, only: [:index, :show]
	
  def index
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
	before_action :require_admin, only: [:index, :show, :new, :create, :edit, :update, :destroy]
	def index
		@questions = Question.all
    	@questions.order!('id DESC')

    	respond_to do |format|
      		format.html
      		format.xml  { render xml: @questions }
    end
  end

  # GET /questions/1
  # GET /questions/1.xml
  def show
    @question = Question.find(params[:id])
    
    respond_to do |format|
      format.html 
      format.xml  { render xml: @question }
    end
  end

  # GET /questions/new
  # GET /questions/new.xml
  def new
    @question = Question.new
    @question.save
    respond_to do |format|
      format.html 
      format.xml  { render xml: @question }
    end
  end

  # GET /questions/1/edit
  def edit
    @question = Question.find(params[:id])
  end

  # POST /questions
  # POST /questions.xml
  def create
    @question = Question.new

    respond_to do |format|
      if @question.save
        format.html { redirect_to(@question, notice: 'Question was successfully created.') }
        format.xml  { render xml: @question, status: :created, location: @question }
      else
        format.html { render action: "new" }
        format.xml  { render xml: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /questions/1
  # PUT /questions/1.xml
  def update
    @question = Question.find(params[:id])

    respond_to do |format|
      if @question.update_attributes(params.require(:question).permit(:text))
        format.html { redirect_to(@question, notice: 'Question was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render action: "edit" }
        format.xml  { render xml: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.xml
  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    respond_to do |format|
      format.html { redirect_to(questions_url) }
      format.xml  { head :ok }
    end
  end

  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		@user = User.find_by_email(params[:session][:email])
		if @user && @user.authenticate(params[:session][:password])
			session[:user_id] = @user.id
			redirect_to '/'
		else
			redirect_to 'login'
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to '/'
	end
end

app/controllers/survey_controller.rb
class SurveyController < ApplicationController
	before_action :require_user, only: [:index, :start, :question, :answer, :result]
	def index
  	end
  
  	def start
  		total = params[:number].to_i
		all = Question.all.map {|x| x.id}
		session[:questions] = all.sort_by{rand}[0..(total-1)]
	 
		session[:total] = total
		session[:current] = 0
		session[:correct] = 0
	 
		redirect_to action: "question"
  	end

  	def question
  		@current = session[:current]
		@total = session[:total]
	 
		if @current >= @total
			redirect_to action: "result"
		return
		end
	 
		@question = Question.find(session[:questions][@current])
		@answers = @question.answers.sort_by{rand}
		 
		session[:question] = @question
		session[:answers] = @answers
  	end

  	def answer
  		@current = session[:current]
		@total   = session[:total]
	 
		answerid = params[:answer]
	 
		@question = Question.find(session[:questions][@current])
		session[:question] = @question
		@answers  = session[:answers]
	 
		@answer = answerid ? Answer.find(answerid) : nil
		if @answer and @answer.correct
			@correct = true
			session[:correct] += 1
		else
			@correct = false
		end
	 
		session[:current] += 1
  	end

  	def result
  		@correct = session[:correct]
		@total   = session[:total]
	 	
		@score = @correct * 100 / @total
		@user = User.find(session[:user_id])

		UserMailer.test_result(@user).deliver
	end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			UserMailer.invitation(@user).deliver
			session[:user_id] = @user.id
			redirect_to '/'
		else
			redirect_to '/signup'
		end
	end

	def edit
		@user = User.find(session[:user_id])
	end

	def update
		@user = User.find(session[:user_id])
		if @user.update_attributes(user_params)
			flash[:success] = "Profile updated"
			redirect_to root_path
		else
			flash[:notice] = "Your password and password confirmation are not identical"
			render "edit"
		end
	end
	
				
	private

	def user_params
		params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
	end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/survey_helper.rb
module SurveyHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="center jumbotron">
<h2><%= link_to "Survey Page", {controller: "survey", action: "index"} %></h2>
<br>
<% if current_user && current_user.admin? %>
	<h2><%= link_to 'Management', questions_path %></h2>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Countdown</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="header">
      <div class="container">
      <div class="nav pull-right">
          <% if current_user %>
          <ul>
            <li><%= current_user.email %></li>
            <li><%= link_to "Profile", "edit" %></li>
            <li><%= link_to "Log out", logout_path, method: "delete" %></li>
            <h1>Hello, <%= current_user.first_name %></h1></p>
          </ul>
          <% else %>
          <ul>
            <li><%= link_to "Login", 'login' %></a></li>
        <li><%= link_to "Signup", 'signup' %></a></li>
    </ul>
  <% end %>
          
      </div>
      </div>
</div>
<%= yield %>

</body>
</html>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>
      
      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_area :text, size: "50x3" %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<div class="center">
<h1>Editing question</h1>

<%= render 'form' %>
</div>
<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

<% content_for(:title) do %>
  Edit Question
<% end %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>
<div class="center">
<h1>Listing questions</h1>

<p>Total: <%= @questions.size %></p>
<p><%= link_to 'New Question', new_question_path %></p>

<table border="1" align="center">
  <tr>
    <th>Text</th>
    <th>Answers</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @questions.each do |question| %>
  <tr>
    <td><%= question.text %></td>
    <td>
      <ul>
        <% question.answers.each do |answer| %>
          <li>
            <%= answer.text %>
            <% if answer.correct %> (Correct) <% end %>
          </li>
        <% end %>
      </ul>
    </td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
<% end %>
</table>
<br>
</div>
<%= link_to 'Back', root_path %>

app/views/questions/new.html.erb
<div class="center">
<h1>New question</h1>

<%= render 'form' %>
</div>
<%= link_to 'Back', questions_path %>

<% content_for(:title) do %>
  New Question
<% end %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>
<div class="center">
<p>
  <b>Text:</b>
  <%= @question.text %>
</p>

<h4>Answers</h4>
<ul>
  <% @question.answers.each do |answer| %>
	 <li>
		<%= answer.text %>
		<% if answer.correct %> (Correct) <% end %>
		
		<%= form_tag({controller: "answers", action: "destroy"}) do %>
		  <%= hidden_field_tag :question, @question.id %>
		  <%= hidden_field_tag :answer, answer.id %>
		  <%= submit_tag "Delete" %>
		<% end %>
		
	 </li>
  <% end %>
</ul>

<h5>New Answer</h5>
<%= form_tag({controller: "answers", action: "create"}) do %>
  <%= hidden_field_tag :question, @question.id %>
  
  <%= label_tag :text, "Text" %><br />
  <%= text_field_tag :text %>
  <br />
  <%= check_box_tag :correct %>
  <%= label_tag :correct, "Correct" %>
  <br />
  <%= submit_tag "Create" %>
<% end %>
</div>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>

<% content_for(:title) do %>
  Question Details
<% end %>

app/views/survey/answer.html.erb
<div class="center">
<h1>Question <%= @current + 1 %> of <%= @total %></h1>
<p id="question"><%= @question.text %></p>

<div id="feedback-answers">
  <% @question.answers.each do |answer| %>
	 <% if answer.correct %>
		<p class="correct feedback-answer">
	 <% elsif answer == @answer %>
		<p class="incorrect feedback-answer">
	 <% else %>
		<p class="feedback-answer">
	 <% end %>
		<%= answer.text %>
	 </p>
  <% end %>
</div>

<p class="feedback">
  <% if @correct %>
	 Correct!
  <% else %>
	 Incorrect.
  <% end %>
</p>

<%= form_tag({controller: "survey", action: "question"}) do %>
 
	 <%= submit_tag("Continue", class: "submit") %>
  </div>
<% end %>

app/views/survey/index.html.erb
<div class="center">
<h1>Start Survey</h1>

<%= form_tag({controller: "survey",
				  action: "start"}) do %>
  <p><%= label_tag(:number, "How many questions do you want in the survey?", id: "question") %></p>
  <p class="center"><%= select_tag(:number, options_for_select((1..10).map {|x| [x, x]}), id: "count") %> <br /></p>
  
  
	 <%= submit_tag "Start!", class: "submit"%>
  </div>
<% end %>

<% content_for(:title) do %>
  Start Survey
<% end %>

app/views/survey/question.html.erb
<div class="center">
<h1>Question <%= @current + 1 %> of <%= @total %></h1>
<p id="question"><%= @question.text %></p>

<%= form_tag({controller: "survey", action: "answer"}) do %>
  <% @answers.each do |answer| %>
	 <p class="answer">
		<%= radio_button_tag(:answer, answer.id) %>
		<%= label_tag("answer_".concat(answer.id.to_s).to_sym, answer.text) %>
	 </p>
  <% end %>
  
  
	 <%= submit_tag("Continue", class: "submit") %>
  </div>
<% end %>

<%= link_to "Back", root_path %>

<% content_for(:title) do %>
  Question <%= @current + 1 %> of <%= @total %>
<% end %>

app/views/survey/result.html.erb
<div class="center">
<h1>Survey Results</h1>
<p id="question">You answered correctly <%= @correct %> out of <%= @total %> questions.</p>

<p id="score"><%= @score %>%</p>

<%= form_tag({controller: "survey", action: "index"}, method: "get") do %>
  
	 <%= submit_tag("Take another", class: "submit") %>
  </div>
<% end %>

<%= link_to "Back", root_path %>
<% content_for(:title) do %>
  Survey Results
<% end %>

app/views/users/edit.html.erb
<h1>Update your profile</h1>
<p id="notice"><%= notice %></p>
<%= form_for(@user) do |f| %>

<%= f.text_field :first_name, placeholder: "First name" %>
<%= f.text_field :last_name, placeholder: "Last name" %>
<%= f.email_field :email, placeholder: "Email" %>
<%= f.password_field :password, placeholder: "Password" %>
<%= f.password_field :password_confirmation, placeholder: "Password confirmation" %>
<%= f.submit "Update profile", class: "btn-submit" %>
<% end %>
<br>
<%= link_to 'Back', root_path %>

app/views/users/new.html.erb
<div class="login">
  <div class="container">
    <div class="form">

    <h1>Sign up</h1>

 <%= form_for(@user) do |f| %>
      <%= f.text_field :first_name, placeholder: "First name" %>
      <%= f.text_field :last_name, placeholder:  "Last name" %>
      <%= f.email_field :email, placeholder: "Email" %>
      <%= f.password_field :password, placeholder: "Password" %>
      <%= f.submit "Create an account", class: "btn-submit" %>
    <% end %>
  
    </div>
  </div>
</div>